version: '3'

services:
  db:
    image: postgres
    hostname: "postgres"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: root_password
    networks:
        - default
          
  keycloak-1:
    image: keycloak_image:3.2.1.Final
    hostname: "keycloak-1"
    environment:
      KEYCLOAK_LOGLEVEL: DEBUG
      POSTGRES_PORT_5432_TCP_ADDR: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password      
    ports:
        - "8080:8080"
    networks:
        - default
    deploy:
      replicas: 1
   

  keycloak-2:
    image: keycloak_image:3.2.1.Final
    hostname: "keycloak-2"
    environment:
      KEYCLOAK_LOGLEVEL: DEBUG
      POSTGRES_PORT_5432_TCP_ADDR: keycloak_db
      POSTGRES_USER: keycloak 
      POSTGRES_PASSWORD: password
    ports:
        - "8081:8080"
    networks:
        - default
    deploy:
      replicas: 1
      
networks:
 default:
   driver: overlay

