language: java

cache:
  directories:
    - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/org/keycloak

env:
  global:
    - MAVEN_SKIP_RC=true
    - MAVEN_OPTS="-Xms512m -Xmx2048m"
  matrix:
    - TESTS=group1
    - TESTS=group2
    - TESTS=group3
    - TESTS=group4
    - TESTS=old

jdk:
  - oraclejdk8

before_script:
  - export MAVEN_SKIP_RC=true

install: 
  - travis_wait 60 mvn install --no-snapshot-updates -Pdistribution -DskipTestsuite -B -V -q

script:
  - ./travis-run-tests.sh $TESTS

sudo: false
